import type { Node, Edge } from '@xyflow/react'
import type { InputFile } from '@/types/flow'
import type { AgentStep } from '@/types/agent'
import { NON_MULTIMODAL_MODELS } from '@/types/model'
import { buildFullSystemPrompt } from '@/lib/personality-injector'
import { readPrivateMemory } from '@/lib/memory-updater'


export async function getWorkspaceContext(flowId: string, nodeId: string): Promise<string> {
  if (!flowId) return '';
  try {
    const res = await fetch(`/api/workspace/${flowId}?nodeId=${nodeId}`);
    if (!res.ok) return '';
    const { context } = await res.json();
    return context || '';
  } catch {
    return '';
  }
}

export async function executeAgentNode(
  node: Node,
  input: string,
  inputImages: InputFile[],
  workspaceContext: string,
  onStep: (step: AgentStep) => void,
  onToken: (token: string) => void,
  defaultProvider = 'anthropic',
  signal?: AbortSignal,
): Promise<string> {
  const data = node.data as import('@/types/flow').AgentNodeData
  const personality = data.personality
  const individualName = data.individualName
  const flowId = data._flowId || ''
  const overridePrompt = data._overrideSystemPrompt

  let basePrompt: string
  if (overridePrompt) {
    // Packed executor already built the full prompt with memory injection
    basePrompt = overridePrompt
  } else {
    const privateMemory = await readPrivateMemory(flowId, node.id, individualName)
    const rawPrompt = (data.systemPrompt as string) || 'You are a helpful assistant.'
    basePrompt = buildFullSystemPrompt(personality, rawPrompt, privateMemory)
  }
  const timeInfo = `[Current Time: ${new Date().toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', dateStyle: 'full', timeStyle: 'short' })}]`
  const systemPrompt = workspaceContext
    ? `${timeInfo}\n${workspaceContext}\n\n${basePrompt}`
    : `${timeInfo}\n\n${basePrompt}`

  // Auto-describe images for non-multimodal models
  const modelName = (data.model as string) || 'claude-sonnet-4-6'
  let effectiveInput = input
  let effectiveImages = inputImages
  if (inputImages.length > 0 && NON_MULTIMODAL_MODELS.has(modelName)) {
    try {
      const descRes = await fetch('/api/describe-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        signal,
        body: JSON.stringify({
          images: inputImages.map(f => ({ base64: f.base64, mimeType: f.mimeType, name: f.name })),
        }),
      })
      if (descRes.ok) {
        const { descriptions } = await descRes.json() as { descriptions: string[] }
        if (descriptions.length > 0) {
          const descBlock = `[The following image descriptions were generated by an AI vision model. Treat them as the actual image content — you DO have access to these images through these descriptions.]\n\n${descriptions.join('\n')}`
          effectiveInput = `${descBlock}\n\n${input}`
          effectiveImages = [] // Don't pass images to non-multimodal model
        }
      }
    } catch {
      // If description fails, pass input as-is (images will be ignored by the model anyway)
    }
  }

  const response = await fetch('/api/agent/run', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    signal,
    body: JSON.stringify({
      config: {
        id: node.id,
        name: (data.label as string) || 'Agent',
        systemPrompt,
        model: {
          provider: data.provider || defaultProvider,
          model: modelName,
          apiKey: '',
          temperature: (data.temperature as number) ?? 0.7,
        },
        maxIterations: (data.maxIterations as number) || 10,
      },
      goal: effectiveInput,
      inputImages: effectiveImages.map(f => ({ base64: f.base64, mimeType: f.mimeType, name: f.name })),
      enabledTools: (data.enabledTools as string[]) || [],
      enabledSkills: [],          // built-in subagent skills (not used in canvas nodes)
      enabledFileSkills: (data.enabledSkills as string[]) || [],
    }),
  })

  if (!response.ok) {
    const errBody = await response.json().catch(() => ({ error: 'Agent call failed' })) as { error?: string }
    throw new Error(errBody.error || `HTTP ${response.status}`)
  }
  if (!response.body) throw new Error('No response body')

  const reader = response.body.getReader()
  const decoder = new TextDecoder()
  let finalOutput = ''
  let tokenUsage: { inputTokens: number; outputTokens: number } | null = null

  // Cancel the reader when abort signal fires (stops SSE consumption)
  const onAbort = () => { reader.cancel().catch(() => {}) }
  signal?.addEventListener('abort', onAbort, { once: true })

  try {
    while (true) {
      if (signal?.aborted) break
      const { done, value } = await reader.read()
      if (done) break

      const lines = decoder.decode(value).split('\n\n').filter(Boolean)
      for (const line of lines) {
        if (!line.startsWith('data: ')) continue
        let event: { type: string; data?: unknown }
        try { event = JSON.parse(line.slice(6)) as { type: string; data?: unknown } } catch { continue }

        if (event.type === 'error') throw new Error((event.data as string) || 'Agent error')
        if (event.type === 'token') onToken(event.data as string)
        if (event.type === 'step') {
          const step = event.data as AgentStep
          onStep(step)
          if (step.type === 'done') finalOutput = step.content
        }
        if (event.type === 'usage') tokenUsage = event.data as { inputTokens: number; outputTokens: number }
        if (event.type === 'done') finalOutput = (event.data as string) || finalOutput
      }
    }
  } finally {
    signal?.removeEventListener('abort', onAbort)
  }

  // Store token usage on the node for dashboard tracking
  if (tokenUsage) {
    const { useFlowStore } = await import('@/store/flowStore')
    const store = useFlowStore.getState()
    store.setNodes(store.nodes.map(n =>
      n.id === node.id ? { ...n, data: { ...n.data, tokenUsage } } : n
    ))
  }

  return finalOutput
}

export async function executeConditionNode(
  node: Node,
  input: string,
  defaultProvider = 'anthropic',
): Promise<boolean> {
  const data = node.data as import('@/types/flow').ConditionNodeData
  const mode: 'natural' | 'expression' = data.conditionMode || 'natural'
  const condition: string = data.conditionValue || ''

  if (!condition.trim()) return true

  // Priority: node config > settings conditionProvider > defaultProvider
  // Fetch condition-specific provider from settings if not set on the node
  const LIGHT_MODELS: Record<string, string> = {
    anthropic: 'claude-haiku-4-5',
    openai: 'gpt-4.1-nano',
    deepseek: 'deepseek-chat',
    google: 'gemini-2.5-flash-lite',
    minimax: 'MiniMax-M2.7-highspeed',
  }
  let provider = data.provider || ''
  let model = data.model || ''
  if (!provider) {
    // Try condition-specific setting
    try {
      const res = await fetch('/api/settings')
      if (res.ok) {
        const settings = await res.json()
        if (settings.conditionProvider) {
          provider = settings.conditionProvider
          model = settings.conditionModel || LIGHT_MODELS[provider] || ''
        }
      }
    } catch { /* ignore */ }
  }
  if (!provider) provider = defaultProvider
  if (!model) model = LIGHT_MODELS[provider] || 'claude-haiku-4-5'

  const res = await fetch('/api/condition/eval', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ input, condition, mode, provider, model }),
  })

  if (!res.ok) {
    const errBody = await res.json().catch(() => ({ error: 'Condition evaluation failed' })) as { error?: string }
    throw new Error(`Condition: ${errBody.error || `HTTP ${res.status}`}`)
  }
  const { result } = await res.json()
  return !!result
}

/**
 * Dispatcher node: use LLM to split upstream content into per-target outputs.
 * Calls /api/dispatcher server route to avoid pulling Node.js modules into client bundle.
 * Returns a Record<targetNodeId, string> for handleOutputs.
 */
export async function executeDispatcher(
  node: Node,
  input: string,
  downstreamEdges: Edge[],
  _allEdges: Edge[],
  _defaultProvider: string,
  addLog: (log: { nodeName: string; nodeType: string; type: 'think' | 'act' | 'observe' | 'system'; content: string }) => void,
  signal?: AbortSignal,
): Promise<Record<string, string>> {
  const { useFlowStore } = await import('@/store/flowStore')
  const allNodes = useFlowStore.getState().nodes

  const targets = downstreamEdges.map(e => {
    const tNode = allNodes.find(n => n.id === e.target)
    return {
      id: e.target,
      label: (tNode?.data?.label as string) || e.target,
      promptSummary: ((tNode?.data?.systemPrompt as string) || '').slice(0, 150),
    }
  })

  addLog({
    nodeName: (node.data?.label as string) || 'Dispatcher',
    nodeType: 'dispatcher', type: 'system',
    content: `Dispatching to ${targets.length} targets: ${targets.map(t => t.label).join(', ')}`,
  })

  try {
    const res = await fetch('/api/dispatcher', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      signal,
      body: JSON.stringify({ input, targets }),
    })

    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: 'Dispatch API failed' })) as { error?: string }
      throw new Error(err.error || `HTTP ${res.status}`)
    }

    const { result } = await res.json() as { result: Record<string, string> }

    // Store dispatch results on the node for UI display
    useFlowStore.getState().setNodes(
      useFlowStore.getState().nodes.map(n =>
        n.id === node.id ? { ...n, data: { ...n.data, dispatchResults: result } } : n
      )
    )

    // Log each target's dispatched content
    for (const target of targets) {
      const content = result[target.id] || '(empty)'
      addLog({
        nodeName: (node.data?.label as string) || 'Dispatcher',
        nodeType: 'dispatcher', type: 'act',
        content: `→ ${target.label}:\n${content.slice(0, 500)}${content.length > 500 ? '...' : ''}`,
      })
    }

    addLog({
      nodeName: (node.data?.label as string) || 'Dispatcher',
      nodeType: 'dispatcher', type: 'system',
      content: `Dispatched to ${Object.keys(result).length} target(s).`,
    })

    return result
  } catch (err) {
    addLog({
      nodeName: 'Dispatcher', nodeType: 'dispatcher', type: 'system',
      content: `Dispatch failed: ${err instanceof Error ? err.message : 'unknown'}. Falling back to broadcast.`,
    })
    const fallback: Record<string, string> = {}
    targets.forEach(t => { fallback[t.id] = input })
    return fallback
  }
}
